horasTrabajadas=float(input("Ingresar la cantidad de horas trabajadas en el mes"))
valorHora=int(2800)
salarioMensual=int(horasTrabajadas*valorHora)
print("El salario mensual del operario es: $")
print(salarioMensual)
